# Generated by Django 2.1.4 on 2018-12-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_professor_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='numero_turma',
            field=models.CharField(max_length=4, verbose_name='Número da turma'),
        ),
    ]
