# Generated by Django 2.1.4 on 2018-12-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_curso_professor_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='professor',
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_termino',
            field=models.TimeField(verbose_name='Hora de término'),
        ),
    ]
