# Generated by Django 2.1.4 on 2018-12-21 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0009_auto_20181221_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_curso', models.CharField(max_length=5, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('ementa', models.TextField(verbose_name='Ementa')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga horária')),
                ('valor', models.CharField(max_length=8, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('valor_hora', models.CharField(max_length=8, verbose_name='Valor da hora/aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
            options={
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=4, verbose_name='Turma')),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_termino', models.TimeField(verbose_name='Hora de término')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.Turma'),
        ),
    ]
